### ISSUE TITLE
plans for roadmap

### ISSUE THREAD

**Issue by jjhesk** [jjhesk/UltimateUI#1]
- [ ] integrate from [advanced text view activities](https://github.com/chiuki/advanced-textview)
- [ ] merge with [pixui](https://github.com/neopixl/PixlUI)
- [ ] work on the library with [parked support](https://github.com/gotokatsuya/ParkedTextView)
